point_of_contact: '@snowflakedb/nade'

production: true

distributed: true

modified: false

release_branches: 
  - main

code_owners_file_present: false

jira_project_issue_type: Bug

jira_area: 'Native Apps'

audit_in_scope: false

